### ISSUE TITLE
How to user roles for menu item display

### ISSUE THREAD

**Issue by codeendevor** [MrCMS/Mobile-Friendly-Navigation#1]
Hello,

I would like to only display a menu node if the user has role access to that page, and not show the menu item if user does not have permission to view that page, so basically if a user is logged in i would like to show only the menu items his role allows. I am using MobileFriendlyNavigation app. Any help would be appreciated.

**Comment by Will-Bill** [comment]
Create ACL rules and check the page can be viewed before rendering the navigation item. This will be code changes within MobileFriendlyNavigation app.
